name: Cypress Tests

on:
  push:
    branches:
      - main
      - integration

jobs:
  Cypress-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitCode
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # Specify the Node.js version you are using

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Test
        uses: cypress-io/github-action@v4
        with:
          command: npx cypress run --browser chrome
